#!/bin/bash

# -------------------------------- completion --------------------------------
# complete -c greet greet
declare -a COMMANDS=(foo bar blah)

if [[ -n $COMP_LINE ]]; then
  for cmd in "${COMMANDS[@]}"; do
    # ${cmd:0:${#2}}  <-- looks at the cmd and takes the 0 place up to the
    # length of the command.
   [[ ${cmd:0:${#2}} = "${2,,}" ]] && echo "$cmd"    #{2,,} <-- looks at the second command and auto lower case
  done
  exit
fi

# ------------------------------ end completion ------------------------------

# --------------------------------- functions --------------------------------

_foo() {
  echo would foo
}

_bar() {
  echo would bar
}

_blah() {
  echo would blah with "$1"
}


# -------------------------------- delegation --------------------------------


declare cmd="$1"; shift
for c in "${COMMANDS[@]}"; do
  [[ $c == "$cmd" ]] &&  "_$cmd" "$@" && exit $?
done



