#!/bin/sh

dman(){ #: Use Dmenu to interactively look for and display a man page.
	local Chosen=$(
		man -k . 2> /dev/null | while read Pkg Group _ Desc; do
			# The `#- ` bit fixes entries with botched short descriptions.
			printf '%50s - %s\n' "$Pkg $Group" "${Desc#- }"
		done | dmenu -i -l 30 -fn 'Ubuntu Mono':style=Bold:size=12\
			-nb \#000000 -nf \#ffffff -sb \#550000 -sf \#ffffff
			# Dmenu is using my customizations from i3Config here.
	)

	local FieldCount=0
	local Field Pkg Group
	for Field in $Chosen; do
		FieldCount=$((FieldCount + 1))

		case $FieldCount in
			1) Pkg=$Field ;;
			2) Group=${Field%)} ;;
			*) break ;;
		esac
	done

	man "${Group#(}" "$Pkg" 2> /dev/null
}


dman
