#!/bin/bash

set -e

x_new() {
  printf '%s\n' "$(date +%d/%m/%y): $*"  >> ~/notes
  cat ~/notes | yad --text-info --back=#282c34 --fore=#46d9ff --geometry=1200x800 --title=Notes
}

x_n() {
  x_new "$*"
}
x_show() {
cat ~/notes | yad --text-info --back=#282c34 --fore=#46d9ff --geometry=1200x800 --title=Notes
}

x_s() {
  x_show
}


# ----------------------------------- Usage ----------------------------------
x_usage() {
    local cmds="${COMMANDS[*]}"
    printf "usage: %s (%s)\n" "${0##*/}" "${cmds// /|}"
}


# --------------------- completion and delegation --------------------
while IFS= read -r line; do
    [[ $line =~ ^declare\ -f\ x_ ]] || continue
    COMMANDS+=( "${line##declare -f x_}" )
done < <(declare -F)

if [[ -n $COMP_LINE ]]; then
    line=${COMP_LINE#* }
    for c in "${COMMANDS[@]}"; do
        [[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
    done
    exit
fi

for c in "${COMMANDS[@]}"; do
    if [[ $c == "$EXE" ]]; then
        "x_$EXE" "$@"
        exit $?
    fi
done

declare cmd="$1"; shift
for c in "${COMMANDS[@]}"; do
    if [[ $c == "$cmd" ]]; then
        "x_$cmd" "$@"
        exit $?
    fi
done

x_usage "$@"

