#!/bin/bash

# Simple script to show all currently active devices on the network.wlp5s0
broadcast=$(ip addr show wlp5s0 | awk '$1 == "inet" &&  $4 !~ /^host/ { print $4"/24" }' | uniq)

RED='\033[0;31m'
GRAY='\033[0;37m'
GREEN='\033[0;32m'
NC='\033[0m'

#clear
printf "${GRAY}Executing nmap on home network: ${RED}\n$broadcast\n"
candidates=$(
for brdip in ${broadcast}; do 
	nmap -sP $brdip | awk '$2 == "scan" { print $5 }'
done)
printf "${GRAY}\nFound the following devices: ${GREEN}\n$candidates\n$NC"

